import React, { useState } from "react";
import {
    FileText,
    FileSpreadsheet,
    X,
    Shield,
    AlertTriangle,
    CheckCircle2,
    Calendar,
    Activity,
    User,
    Clock,
    ChevronRight,
    TrendingUp,
    HeartPulse,
    Info,
    Download,
    Eye,
} from "lucide-react";
import RiskBadge from "./RiskBadge";
import { downloadReportPdf, downloadReportExcel } from "../api/reports";

function ReportViewer({ payload, onClose }) {
    const [downloadingPdf, setDownloadingPdf] = useState(false);
    const [downloadingExcel, setDownloadingExcel] = useState(false);
    const [exportError, setExportError] = useState(null);

    if (!payload) return null;

    const {
        report_type,
        report_type_label,
        report_title,
        generated_at,
        generated_by_name,
        generated_by_role,
        athlete,
        assessment,
        data,
        disclaimer,
    } = payload;

    const formattedDate = generated_at
        ? new Date(generated_at).toLocaleString()
        : new Date().toLocaleString();

    async function handleDownloadPdf() {
        try {
            setDownloadingPdf(true);
            setExportError(null);
            await downloadReportPdf(
                report_type,
                athlete.athlete_id,
                assessment?.video_id || null
            );
        } catch (err) {
            console.error("PDF download error:", err);
            setExportError("Failed to export PDF. Please try again.");
        } finally {
            setDownloadingPdf(false);
        }
    }

    async function handleDownloadExcel() {
        try {
            setDownloadingExcel(true);
            setExportError(null);
            await downloadReportExcel(
                report_type,
                athlete.athlete_id,
                assessment?.video_id || null
            );
        } catch (err) {
            console.error("Excel download error:", err);
            setExportError("Failed to export Excel. Please try again.");
        } finally {
            setDownloadingExcel(false);
        }
    }

    return (
        <div className="report-modal-backdrop" onClick={onClose}>
            <div
                className="report-modal-content"
                onClick={(e) => e.stopPropagation()}
            >
                {/* Top Action Header */}
                <div className="report-modal-header">
                    <div className="report-header-info">
                        <div className="report-header-badge">
                            <FileText size={16} />
                            <span>{report_type_label}</span>
                        </div>
                        <h2 className="report-main-title">{report_title}</h2>
                        <div className="report-meta-line">
                            <span>Generated: {formattedDate}</span>
                            <span className="dot-sep">•</span>
                            <span>
                                Generated by: <strong>{generated_by_name}</strong> ({generated_by_role})
                            </span>
                        </div>
                    </div>

                    <div className="report-header-actions">
                        <button
                            type="button"
                            className="btn btn-secondary report-export-btn"
                            onClick={handleDownloadPdf}
                            disabled={downloadingPdf}
                            title="Export as PDF"
                        >
                            <Download size={15} />
                            <span>{downloadingPdf ? "Exporting PDF..." : "Export PDF"}</span>
                        </button>

                        <button
                            type="button"
                            className="btn btn-secondary report-export-btn"
                            onClick={handleDownloadExcel}
                            disabled={downloadingExcel}
                            title="Export as Excel"
                        >
                            <FileSpreadsheet size={15} />
                            <span>{downloadingExcel ? "Exporting Excel..." : "Export Excel"}</span>
                        </button>

                        <button
                            type="button"
                            className="report-modal-close"
                            onClick={onClose}
                            title="Close preview"
                        >
                            <X size={20} />
                        </button>
                    </div>
                </div>

                {exportError && (
                    <div className="report-error-banner">
                        <AlertTriangle size={16} />
                        <span>{exportError}</span>
                    </div>
                )}

                {/* Scrollable Report Body */}
                <div className="report-modal-body">
                    {/* Athlete & Assessment Profile Card */}
                    <div className="report-section-card">
                        <div className="report-card-heading">
                            <User size={18} className="text-primary" />
                            <h3>Athlete & Assessment Information</h3>
                        </div>

                        <div className="report-metadata-grid">
                            <div className="meta-item">
                                <span className="meta-label">Athlete Name</span>
                                <span className="meta-val font-semibold">{athlete.name}</span>
                            </div>
                            <div className="meta-item">
                                <span className="meta-label">Sport / Position</span>
                                <span className="meta-val">{athlete.sport} / {athlete.position}</span>
                            </div>
                            <div className="meta-item">
                                <span className="meta-label">Age / Height / Weight</span>
                                <span className="meta-val">{athlete.age} yrs • {athlete.height} cm • {athlete.weight} kg</span>
                            </div>
                            <div className="meta-item">
                                <span className="meta-label">Dominant Leg</span>
                                <span className="meta-val">{athlete.dominant_leg}</span>
                            </div>
                            <div className="meta-item">
                                <span className="meta-label">Injury Status</span>
                                <span className="meta-val font-medium">{athlete.injury_status}</span>
                            </div>
                            <div className="meta-item">
                                <span className="meta-label">Assigned Coach</span>
                                <span className="meta-val">{athlete.coach_name}</span>
                            </div>

                            {assessment && (
                                <>
                                    <div className="meta-item">
                                        <span className="meta-label">Assessment Video</span>
                                        <span className="meta-val font-medium">{assessment.title || assessment.original_filename}</span>
                                    </div>
                                    <div className="meta-item">
                                        <span className="meta-label">Assessment Date</span>
                                        <span className="meta-val">
                                            {assessment.assessment_date
                                                ? new Date(assessment.assessment_date).toLocaleDateString()
                                                : "Data unavailable"}
                                        </span>
                                    </div>
                                    <div className="meta-item">
                                        <span className="meta-label">Video Metadata</span>
                                        <span className="meta-val">{assessment.fps} FPS • {assessment.duration_seconds}s • {assessment.resolution}</span>
                                    </div>
                                    <div className="meta-item">
                                        <span className="meta-label">Frames Processed</span>
                                        <span className="meta-val">{assessment.frames_processed} frames</span>
                                    </div>
                                </>
                            )}
                        </div>
                    </div>

                    {/* TYPE 1: INJURY RISK REPORT */}
                    {report_type === "INJURY_RISK" && (
                        <>
                            <div className="report-section-card">
                                <div className="report-card-heading">
                                    <Shield size={18} className="text-primary" />
                                    <h3>1. Overall Injury Risk Screening Classification</h3>
                                </div>

                                <div className="report-risk-summary-box">
                                    <div className="risk-score-display">
                                        <span className="risk-score-number">{data.overall_risk_score}</span>
                                        <span className="risk-score-max">/ 100</span>
                                    </div>
                                    <div className="risk-level-badge-container">
                                        <RiskBadge level={data.risk_level} />
                                        <p className="risk-summary-text">{data.assessment_summary}</p>
                                    </div>
                                </div>

                                {data.risk_factors && data.risk_factors.length > 0 && (
                                    <div className="mt-4">
                                        <h4 className="report-subheading">Contributing Screening Factors (5-Factor Model)</h4>
                                        <div className="report-table-wrapper">
                                            <table className="report-table">
                                                <thead>
                                                    <tr>
                                                        <th>Factor</th>
                                                        <th>Score</th>
                                                        <th>Status</th>
                                                        <th>Description</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {data.risk_factors.map((f, i) => (
                                                        <tr key={i}>
                                                            <td className="font-medium">{f.factor_name}</td>
                                                            <td>{f.contribution_score}</td>
                                                            <td>
                                                                <span className={`status-pill ${f.status === "Elevated" ? "pill-danger" : "pill-success"}`}>
                                                                    {f.status}
                                                                </span>
                                                            </td>
                                                            <td className="text-muted">{f.description}</td>
                                                        </tr>
                                                    ))}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                )}
                            </div>

                            {/* Recommendations */}
                            {data.recommendations && (
                                <div className="report-section-card">
                                    <div className="report-card-heading">
                                        <Activity size={18} className="text-primary" />
                                        <h3>2. Corrective Action Plan Recommendations</h3>
                                    </div>

                                    <div className="recommendations-list-preview">
                                        {[
                                            ...(data.recommendations.exercise_recommendations || []),
                                            ...(data.recommendations.mobility_recommendations || []),
                                            ...(data.recommendations.strengthening_recommendations || []),
                                        ].slice(0, 6).map((rec, i) => (
                                            <div key={i} className="rec-preview-item">
                                                <div className="rec-preview-header">
                                                    <span className={`rec-priority-tag priority-${rec.priority?.toLowerCase()}`}>
                                                        {rec.priority?.toUpperCase()} PRIORITY
                                                    </span>
                                                    <span className="rec-category-tag">{rec.category}</span>
                                                    <h4 className="rec-title">{rec.title}</h4>
                                                </div>
                                                <p className="rec-desc">{rec.description}</p>
                                                {rec.exercises && rec.exercises.length > 0 && (
                                                    <div className="rec-drills">
                                                        <strong>Recommended Action:</strong> {rec.exercises.join(", ")}
                                                    </div>
                                                )}
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}
                        </>
                    )}

                    {/* TYPE 2: BIOMECHANICAL REPORT */}
                    {report_type === "BIOMECHANICAL" && (
                        <>
                            <div className="report-section-card">
                                <div className="report-card-heading">
                                    <Activity size={18} className="text-primary" />
                                    <h3>1. Biomechanical Scores & Motion Metrics</h3>
                                </div>

                                <div className="report-metrics-grid">
                                    <div className="metric-box">
                                        <span className="metric-label">Symmetry Score</span>
                                        <span className="metric-val">{data.symmetry_score}</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Fatigue Score</span>
                                        <span className="metric-val">{data.fatigue_score}</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Movement Quality</span>
                                        <span className="metric-val">{data.movement_quality}</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Joint Alignment</span>
                                        <span className="metric-val">{data.joint_alignment}</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Trunk Lean</span>
                                        <span className="metric-val">{data.trunk_lean}°</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Knee Valgus</span>
                                        <span className="metric-val">{data.knee_valgus}°</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Hip Stability</span>
                                        <span className="metric-val">{data.hip_stability}</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Stride Length</span>
                                        <span className="metric-val">{data.stride_length} m</span>
                                    </div>
                                </div>
                            </div>

                            {data.asymmetries && data.asymmetries.length > 0 && (
                                <div className="report-section-card">
                                    <div className="report-card-heading">
                                        <HeartPulse size={18} className="text-primary" />
                                        <h3>2. Bilateral Asymmetry Findings</h3>
                                    </div>

                                    <div className="report-table-wrapper">
                                        <table className="report-table">
                                            <thead>
                                                <tr>
                                                    <th>Body Region</th>
                                                    <th>Left</th>
                                                    <th>Right</th>
                                                    <th>Difference</th>
                                                    <th>Status</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {data.asymmetries.map((a, i) => (
                                                    <tr key={i}>
                                                        <td className="font-medium">{a.body_region}</td>
                                                        <td>{a.left_value}</td>
                                                        <td>{a.right_value}</td>
                                                        <td>{a.asymmetry_percentage}°</td>
                                                        <td>
                                                            <span className={`status-pill ${a.status === "Asymmetric" ? "pill-danger" : "pill-success"}`}>
                                                                {a.status}
                                                            </span>
                                                        </td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            )}
                        </>
                    )}

                    {/* TYPE 3: MOVEMENT ANALYSIS REPORT */}
                    {report_type === "MOVEMENT" && (
                        <div className="report-section-card">
                            <div className="report-card-heading">
                                <Activity size={18} className="text-primary" />
                                <h3>1. Landing Error Scoring System (LESS) Approximation</h3>
                            </div>

                            <div className="report-less-score-banner">
                                <div>
                                    <span className="less-score-headline">LESS Score: {data.less_total_score} / {data.less_max_score}</span>
                                    <span className="less-class-headline">Classification: {data.less_classification}</span>
                                </div>
                            </div>

                            {data.less_items && data.less_items.length > 0 && (
                                <div className="report-table-wrapper mt-4">
                                    <table className="report-table">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Item Name</th>
                                                <th>Status</th>
                                                <th>Score</th>
                                                <th>Measured</th>
                                                <th>Details</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {data.less_items.map((it, i) => (
                                                <tr key={i}>
                                                    <td>{it.item_number}</td>
                                                    <td className="font-medium">{it.item_name}</td>
                                                    <td>
                                                        <span className={`status-pill ${it.status === "PASS" ? "pill-success" : (it.status === "ERROR" ? "pill-danger" : "pill-muted")}`}>
                                                            {it.status}
                                                        </span>
                                                    </td>
                                                    <td>{it.score !== null ? it.score : "-"}</td>
                                                    <td>{it.measured_value}</td>
                                                    <td className="text-muted">{it.reason || "Criteria met"}</td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            )}
                        </div>
                    )}

                    {/* TYPE 4: ATHLETE PERFORMANCE REPORT */}
                    {report_type === "ATHLETE_PERFORMANCE" && (
                        <>
                            <div className="report-section-card">
                                <div className="report-card-heading">
                                    <TrendingUp size={18} className="text-primary" />
                                    <h3>1. Training Workload & Fatigue Profile</h3>
                                </div>

                                <div className="report-metrics-grid">
                                    <div className="metric-box">
                                        <span className="metric-label">Sessions / Week</span>
                                        <span className="metric-val">{data.training_sessions_per_week}</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Avg Session Duration</span>
                                        <span className="metric-val">{data.average_session_duration} min</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Avg RPE</span>
                                        <span className="metric-val">{data.average_session_rpe} / 10</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Weekly Training Load</span>
                                        <span className="metric-val">{data.weekly_training_load} AU</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Current Fatigue</span>
                                        <span className="metric-val">{data.current_fatigue_level} / 10</span>
                                    </div>
                                </div>
                            </div>

                            {data.assessment_history && data.assessment_history.length > 0 && (
                                <div className="report-section-card">
                                    <div className="report-card-heading">
                                        <Calendar size={18} className="text-primary" />
                                        <h3>2. Longitudinal Assessment History</h3>
                                    </div>

                                    <div className="report-table-wrapper">
                                        <table className="report-table">
                                            <thead>
                                                <tr>
                                                    <th>Date</th>
                                                    <th>Assessment Title</th>
                                                    <th>Risk Score</th>
                                                    <th>Risk Level</th>
                                                    <th>LESS Score</th>
                                                    <th>Symmetry</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {data.assessment_history.map((h, i) => (
                                                    <tr key={i}>
                                                        <td>{h.date ? new Date(h.date).toLocaleDateString() : "N/A"}</td>
                                                        <td className="font-medium">{h.title}</td>
                                                        <td>{h.risk_score}</td>
                                                        <td><RiskBadge level={h.risk_level} /></td>
                                                        <td>{h.less_score}</td>
                                                        <td>{h.symmetry_score}</td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            )}
                        </>
                    )}

                    {/* TYPE 5: REHABILITATION REPORT */}
                    {report_type === "REHABILITATION" && (
                        <>
                            <div className="report-section-card">
                                <div className="report-card-heading">
                                    <HeartPulse size={18} className="text-primary" />
                                    <h3>1. Rehabilitation & Reassessment Status</h3>
                                </div>

                                <div className="report-metrics-grid">
                                    <div className="metric-box">
                                        <span className="metric-label">Current Injury Status</span>
                                        <span className="metric-val font-semibold">{data.current_injury_status}</span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Needs Reassessment</span>
                                        <span className="metric-val font-semibold">
                                            {data.needs_reassessment ? "YES (>14 days)" : "NO (Current)"}
                                        </span>
                                    </div>
                                    <div className="metric-box">
                                        <span className="metric-label">Days Since Screening</span>
                                        <span className="metric-val">{data.days_since_last_assessment} days</span>
                                    </div>
                                </div>

                                <p className="mt-3 text-sm text-muted">{data.reassessment_recommendation}</p>
                            </div>

                            {data.injury_records && data.injury_records.length > 0 && (
                                <div className="report-section-card">
                                    <div className="report-card-heading">
                                        <Activity size={18} className="text-primary" />
                                        <h3>2. Documented Injury Records</h3>
                                    </div>

                                    <div className="report-table-wrapper">
                                        <table className="report-table">
                                            <thead>
                                                <tr>
                                                    <th>Injury Type</th>
                                                    <th>Body Part</th>
                                                    <th>Severity</th>
                                                    <th>Date</th>
                                                    <th>Recovery</th>
                                                    <th>Status</th>
                                                    <th>Remarks</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {data.injury_records.map((inj, i) => (
                                                    <tr key={i}>
                                                        <td className="font-medium">{inj.injury_type}</td>
                                                        <td>{inj.body_part}</td>
                                                        <td>{inj.severity}</td>
                                                        <td>{inj.injury_date}</td>
                                                        <td>{inj.recovery_date}</td>
                                                        <td><span className="status-pill pill-success">{inj.status}</span></td>
                                                        <td className="text-muted">{inj.remarks}</td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            )}

                            {data.rehabilitation_notes && data.rehabilitation_notes !== "Data unavailable" && (
                                <div className="report-section-card">
                                    <div className="report-card-heading">
                                        <FileText size={18} className="text-primary" />
                                        <h3>3. Coaching / Rehabilitation Notes</h3>
                                    </div>
                                    <p className="text-sm text-slate-700 bg-slate-50 p-3 rounded-md border border-slate-200">
                                        {data.rehabilitation_notes}
                                    </p>
                                </div>
                            )}
                        </>
                    )}

                    {/* AI Screening Disclaimer */}
                    <div className="report-disclaimer-card">
                        <div className="disclaimer-icon">
                            <Info size={18} />
                        </div>
                        <div className="disclaimer-content">
                            <h4>AI Screening Notice</h4>
                            <p>{disclaimer}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default ReportViewer;
